GET http://localhost:3000/

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlZHJvIiwiaWF0IjoxNzQzOTEzNjc3fQ.dtXBS-5H3BsAnNUqzO19A90_KJTxTd2a98hHQ4dD-Sg

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Pedro"
}